PAGE_ICON = ":books:"
PAGE_TITLE = "Chat with multiple PDFs"
PDF_UPLOAD_MSG = "Upload your PDFs here and click on 'Process'"
PROCESSING_MSG = "Processing"
SUB_HEADER_TEXT = "Your documents"
HEADER_TEXT = "Chat with multiple PDFs :books:"
TEXT_INPUT_PROMPT = "Ask a question about your documents:"
